language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git clone https://github.com/ktxsoftware/koremake.git
  - git clone https://github.com/ktxsoftware/nodejs_bin.git
  - nodejs_bin/copysysbin.sh
script: nodejs_bin/node koremake/koremake.js --compile
